apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-app-ingress
  namespace: ironhack-project-2
  annotations:
    # Create Route 53 A records for the hostnames pointing at the Ingress Controller's ELB
    # The external dns is already auto-detects hostnames straight from the spec.rules[].host
    # The annptation is here just for consilidation
    external-dns.alpha.kubernetes.io/hostname: vote.alex.ironlabs.online,result.alex.ironlabs.online
    
spec:
  ingressClassName: nginx
  rules:
    - host: vote.alex.ironlabs.online      
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vote-service
                port:
                  number: 80
        
    - host: result.alex.ironlabs.online 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: 
              service: 
                name: result-service
                port:
                  number: 80