apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-deployment
  namespace: ironhack-project-2
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker-container
          image: akemloh/worker:latest
          env:
            - name: REDIS_HOST
              value: "redis-master"
            - name: DB_HOST
              value: "postgres-postgresql-primary"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_NAME
              value: "voting"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password
          

